# Generated by Django 2.1.5 on 2019-07-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='audio',
            field=models.FileField(default=1, upload_to='card_audio/', verbose_name='音声ファイル'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default=1, upload_to='card_images/', verbose_name='画像ファイル'),
            preserve_default=False,
        ),
    ]
