# Generated by Django 2.1.5 on 2019-07-07 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcardapp', '0003_auto_20190706_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardMistaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '間違った問題',
                'verbose_name_plural': '間違った問題',
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.AddField(
            model_name='cardmistaken',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcardapp.Card'),
        ),
        migrations.AddField(
            model_name='cardmistaken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
