# Generated by Django 2.1.5 on 2019-07-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardapp', '0004_auto_20190707_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='category_images/', verbose_name='サムネイル'),
            preserve_default=False,
        ),
    ]
